/*
  Warnings:

  - A unique constraint covering the columns `[username]` on the table `users` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[displayName]` on the table `users` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `displayName` to the `users` table without a default value. This is not possible if the table is not empty.
  - Added the required column `username` to the `users` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "public"."WorkoutType" AS ENUM ('Weights', 'Calisthenics', 'Resistance', 'Yoga', 'Pilates', 'Dance');

-- CreateEnum
CREATE TYPE "public"."Goal" AS ENUM ('GainMuscle', 'IncreaseFlexibility', 'LoseWeight');

-- CreateEnum
CREATE TYPE "public"."MuscleGroup" AS ENUM ('Chest', 'Back', 'Arms', 'Legs', 'Abs');

-- AlterTable
ALTER TABLE "public"."users" ADD COLUMN     "bio" TEXT,
ADD COLUMN     "displayName" TEXT NOT NULL,
ADD COLUMN     "goals" "public"."Goal"[],
ADD COLUMN     "isUsernameAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "location" TEXT,
ADD COLUMN     "muscleGroups" "public"."MuscleGroup"[],
ADD COLUMN     "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "profilePictureUrl" TEXT,
ADD COLUMN     "timezone" TEXT,
ADD COLUMN     "username" TEXT NOT NULL,
ADD COLUMN     "workoutTypes" "public"."WorkoutType"[];

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "public"."users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "users_displayName_key" ON "public"."users"("displayName");
