// lib/models/user_model.dart

class User {
  final int id;
  final String email;
  final String role;
  final String username;
  final String displayName;
  final bool isUsernameAutoGenerated;
  final bool onboardingCompleted;
  final String? bio;

  User({
    required this.id,
    required this.email,
    required this.role,
    required this.username,
    required this.displayName,
    required this.isUsernameAutoGenerated,
    required this.onboardingCompleted,
    this.bio,
  });

 factory User.fromJwt(Map<String, dynamic> jwt) {
  return User(
    id: jwt['id'],
    email: jwt['email'],
    role: jwt['role'],
    username: jwt['username'] ?? '',
    displayName: jwt['displayName'] ?? '',
    isUsernameAutoGenerated: jwt['isUsernameAutoGenerated'] ?? true,
    onboardingCompleted: jwt['onboardingCompleted'] ?? false,
    bio: jwt['bio'],
  );
}

  // This is the exporter method, now updated with all the fields
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'role': role,
      'username': username,
      'displayName': displayName,
      'isUsernameAutoGenerated': isUsernameAutoGenerated,
      'onboardingCompleted': onboardingCompleted,
      'bio': bio,
    };
  }
}