-- AlterTable
ALTER TABLE "public"."users" ADD COLUMN     "lastStreamCompletedAt" TIMESTAMP(3),
ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "notifyBoosts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "profileBoosts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "proteinBars" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "proteinShakes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rubies" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "unlockedGifts" JSONB DEFAULT '{}',
ADD COLUMN     "xp" INTEGER NOT NULL DEFAULT 0;
