// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX26J53dqE0RzrdQXHuRIICYkT3PoVWs8',
    appId: '1:640082759557:web:356d0634b27809b1c1feec',
    messagingSenderId: '640082759557',
    projectId: 'fitneks-live-gifts',
    authDomain: 'fitneks-live-gifts.firebaseapp.com',
    storageBucket: 'fitneks-live-gifts.firebasestorage.app',
  );
}